### ISSUE TITLE
Docu Update JDK -- ERROR anvil.util - uncaught exception in http server loop error

### ISSUE THREAD

**Issue by patrick-gaertner** [anvil-works/anvil-runtime#108]
Hi Guys, 

I am running a docker container with an Anvil app with the following setup: 
* ubuntu:22.04
* openjdk-8-jdk 
* libpq-dev

When I am using the anvil-app-server in Version 1.13.4 everthing works fine. 
Today I tried to update my Docker container and got the version 1.14.0 from PIP. 

With this version I am facing the following error message: 

anvil-1  | [ERROR anvil.util] Reporting uncaught exception in http server loop error, should not happen
anvil-1  | java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
anvil-1  |      at org.httpkit.server.HttpServer.doRead(HttpServer.java:249)
anvil-1  |      at org.httpkit.server.HttpServer.run(HttpServer.java:378)
anvil-1  |      at java.lang.Thread.run(Thread.java:750)
anvil-1  | [INFO  anvil.app-server.run] No downlink connected; postponing check for scheduled tasks
anvil-1  | [INFO  anvil.app-server.dispatch] Launching built-in downlink...
anvil-1  | [ERROR anvil.util] Reporting uncaught exception in http server loop error, should not happen
anvil-1  | java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
anvil-1  |      at org.httpkit.server.HttpServer.doRead(HttpServer.java:249)
anvil-1  |      at org.httpkit.server.HttpServer.run(HttpServer.java:378)
anvil-1  |      at java.lang.Thread.run(Thread.java:750)

After updating my JDK from 8 to 17 the error is gone and everything is working fine. 

So please can you add the minimum version to your documentation? 
The error itself and the solution should be documented with this issue. 

Thanks 
Patrick

**Comment by Manjunath-krishna** [comment]
yup even I had the same issue.

one more think @handle from client code also causing errors in anvil server 
[ERROR anvil.app-server.core] Error report from client code:
NameError: name 'handle' is not defined
